version: "3"

services:
  web:
    image: filler36/feelthenotes-app:latest
    ports:
      - 8000:8000
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
    command: >
      sh -c "python manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL &&
             python ./feelthenotes-app/manage.py makemigrations &&
             python ./feelthenotes-app/manage.py migrate &&
             python ./feelthenotes-app/manage.py runserver 0.0.0.0:8000"
