version: "3"

services:
  feelthenotes-app:
    image: filler36/feelthenotes-app:latest
    ports:
      - 8000:8000
    environment:
      - ZDJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    command: >
      sh -c "python ./feelthenotes-app/manage.py makemigrations &&
             python ./feelthenotes-app/manage.py migrate &&
             python ./feelthenotes-app/manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL &&
             python ./feelthenotes-app/manage.py runserver 0.0.0.0:8000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000
      interval: 60s
      retries: 3
      start_period: 10s
      timeout: 10s
