version: "3"

services:
  feelthenotes-bot:
    image: filler36/feelthenotes-bot:latest
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - ORACLE_HOST=${ORACLE_HOST}
    command: python ./feelthenotes-bot/main.py
