# This is a basic workflow to help you get started with Actions

name: CI/CD workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
 
      - name: Build docker image
        run: docker build -t feelthenotes .

      - name: Create SSH key
        run: |
          echo $ORACLE_USER
          echo $SSH_KNOWN_HOSTS
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          sudo chmod 600 ~/.ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_KEY_PATH: ~/.ssh/private.key
          ORACLE_USER: ${{secrets.ORACLE_USER}}
          ORACLE_HOST: ${{secrets.ORACLE_HOST}}

      - name: connect to oracle host
        run: |
          ssh -i $SSH_KEY_PATH $ORACLE_USER@$ORACLE_HOST
          hostname

      #- name: Run docker container
      #  run: docker run feelthenotes
